version: '3'
services:
    web:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - '.:/Piso'
        tty: true
        stdin_open: true
        depends_on: 
            - db
            - selenium_chrome
        links:
            - db
        environment:
            - 'DATABASE_PASSWORD=password'
            - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
    selenium_chrome:
        image: selenium/standalone-chrome-debug
        logging:
            driver: none
        ports:
            - 4444:4444
    db:
        image: mysql:5.7
        ports:
            - '3306:3306'
        volumes:
            - 'data:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: password
volumes:
    data: